@host = http://localhost:5064

POST {{host}}/auth/login
Content-Type: application/json

{
    "email":"anurag@gmail.com",
    "password":"test@123"
}

###

GET {{host}}/auth/index
Accept: application/json

###
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName":"anurag",
    "lastName":"sinha",
    "email":"anurag@gmail.com",
    "password":"test@123"
}

###
